name:                ogma
version:             0.1.0.0
github:              "AugmenTab/ogma"
license:             BSD-3-Clause
author:              "Tyler Baum"
maintainer:          "tyler.baum@protonmail.com"
copyright:           "2024 Tyler Baum"

language: Haskell2010

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AugmenTab/ogma#readme>

default-extensions:
  - ImportQualifiedPost

dependencies:
  - base
  - bytestring
  - string-interpolate
  - text

ghc-options:
  - -j
  - -Werror
  - -Wall
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fno-warn-orphans

library:
  source-dirs: src
  exposed-modules:
    - Ogma

executables:
  ogma-gen:
    main:        Main.hs
    source-dirs: codegen
    ghc-options: -Wall
    dependencies:
      - base
      - bytestring
      - containers
      - directory
      - filepath
      - http-client
      - http-conduit
      - http-types
      - text
      - unicode-transforms

tests:
  ogma-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ogma
