#!/bin/sh

# Generate once with the default stack.yaml, then test the lib across GHCs.

. scripts/lib/run-in-container.sh

echo "Generating Ogma sources..."
stack --stack-yaml "stack-ghc-9.10.yaml" install ogma:exe:ogma-gen --no-test --no-bench --local-bin-path .codegen-bin
./.codegen-bin/ogma-gen

rm -rf test-all-logs
mkdir test-all-logs

for stack_file in stack-ghc*.yaml; do
  log_file="./test-all-logs/$stack_file.log"

  echo "Testing with $stack_file... "
  if stack --stack-yaml "$stack_file" build ogma:lib --fast --test >"$log_file" 2>&1; then
    echo "Passed"
  else
    SOME_TEST_FAILED=1
    echo "Failed, see $log_file for details"
  fi
done

if [ "$SOME_TEST_FAILED" ]; then
  echo ""
  echo "!!"
  echo "!! At least one test failed above. Be sure to check it out!"
  echo "!!"
  exit 1
fi

