#!/bin/bash

set -e

source scripts/lib/run-in-container.sh

echo "=============================="
echo "====== Generating  Ogma ======"
echo "=============================="

stack build ogma:ogma-gen --only-dependencies --fast "$@"
stack exec ogma-gen

echo "============================"
echo "====== Building  Ogma ======"
echo "============================"

stack build ogma:lib --fast --test "$@"

