#!/bin/bash

echo "================================"
echo "====== Fetching Languages ======"
echo "================================"

docker compose --file compose.language.yml up --abort-on-container-exit

